name: main

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -Dwarnings
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: cargo test
        uses: actions-rs/cargo@v1
        env:
          PROVIDER_URI: ${{ secrets.PROVIDER_URI}}
        with:
          command: test
          args: --verbose

  build_linux:
    timeout-minutes: 30
    name: build_linux_${{ matrix.arch }}_${{matrix.platform}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        platform:
          - gnu
          - musl
    steps:
      - uses: actions/checkout@v3
      - id: target
        run: echo ::set-output name=target::${{ matrix.arch }}-unknown-linux-${{ matrix.platform }}
      - uses: ./.github/actions/setup-cross
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ steps.target.outputs.target }}

  build_macos:
    timeout-minutes: 30
    name: build_macos_${{ matrix.arch }}
    runs-on: macos-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v3
      - id: target
        run: echo ::set-output name=target::${{ matrix.arch }}-apple-darwin
      - name: rust setup
        uses: actions-rs/cargo@v1
        with:
          command: version
      - name: cross setup
        if: matrix.arch == 'aarch64'
        run: |
          rustup target add aarch64-apple-darwin
          echo "JEMALLOC_SYS_WITH_LG_PAGE=14" >> $GITHUB_ENV
      - name: build binary
        run: |
          cargo build --release --target=${{ steps.target.outputs.target }}
