name: release

on:
  push:
    tags:
      - "v*"
  schedule:
    # Release at 00:00 UTC+8
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  create_release:
    name: create release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generated-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get latest tag
        id: get-latest-tag
        run: |
          echo "::set-output name=tag::`gh release list -L 1 | cut -f 1`"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: bump version
        id: generated-tag
        uses: actions/github-script@v6
        with:
          script: |
            if (context.ref.startsWith("refs/tags/")) {
              let tag = context.ref.replace("refs/tags/", "");
              core.setOutput('tag', tag);
              console.log(`This event pushed a tag ${tag}, return directly.`)
              return
            }
            let tag = "${{ steps.get-latest-tag.outputs.tag }}";
            let result = /v(\d+)\.(\d+)\.(\d+)/g.exec(tag);
            if (result === null) {
              throw `The previous tag ${{ steps.get-latest-tag.outputs.tag }} is invalid, ignoring`;
            }
            let major = result[1];
            let minor = result[2];
            let patch = (parseInt(result[3]) + 1).toString();
            let next_tag = `v${major}.${minor}.${patch}-nightly`;
            console.log(`This event is triggered, return generated ${next_tag}.`)
            core.setOutput('tag', next_tag)
      - name: create github release if not exist
        # Reference: https://cli.github.com/manual/gh_release_create
        run: |
          echo "Create a release for ${{ steps.generated-tag.outputs.tag }}"
          gh release create ${{ steps.generated-tag.outputs.tag }} --generate-notes -p
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_macos:
    name: macos assets
    runs-on: macos-11
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    steps:
      - uses: actions/checkout@v3
      - name: get target
        id: target
        run: echo ::set-output name=target::${{ matrix.arch }}-apple-darwin
      - name: rust setup
        uses: actions-rs/cargo@v1
        with:
          command: version
      - name: cross setup
        if: matrix.arch == 'aarch64'
        run: |
          rustup target add aarch64-apple-darwin
          echo "JEMALLOC_SYS_WITH_LG_PAGE=14" >> $GITHUB_ENV
      - name: build binary
        run: |
          cargo build --release --target=${{ steps.target.outputs.target }}
      - name: pack binaries
        run: |
          version="${{ needs.create_release.outputs.version }}"
          target="${{ steps.target.outputs.target }}"
          sudo /usr/sbin/purge
          mkdir -p release/${target}/{bin,schemas,configs}
          cp ./target/${target}/release/ethetl release/${target}/bin/
          rm -f release/${target}/bin/*.d
          cp -r ./schemas/* release/${target}/schemas/
          cp -r ./scripts/deploy/* release/${target}/configs/
          gtar -C ./release/${target} -czvf ethetl-${version}-${target}.tar.gz bin schemas configs
      - name: update release to github
        shell: bash
        # Reference: https://cli.github.com/manual/gh_release_upload
        run: |
          version="${{ needs.create_release.outputs.version }}"
          target="${{ steps.target.outputs.target }}"
          gh release upload ${version} ethetl-${version}-${target}.* --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_linux:
    name: linux assets
    runs-on: ubuntu-latest
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
        platform:
          - musl
          - gnu
    steps:
      - uses: actions/checkout@v3
      - name: get target
        id: target
        run: echo ::set-output name=target::${{ matrix.arch }}-unknown-linux-${{ matrix.platform }}
      - uses: ./.github/actions/setup-cross
      - name: build binary
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ steps.target.outputs.target }}
      - name: pack binaries
        run: |
          version="${{ needs.create_release.outputs.version }}"
          target="${{ steps.target.outputs.target }}"
          mkdir -p release/${target}/{bin,schemas,configs}
          cp ./target/${target}/release/ethetl release/${target}/bin/
          rm -f release/${target}/bin/*.d
          cp -r ./schemas/* release/${target}/schemas/
          cp -r ./scripts/deploy/* release/${target}/configs/
          tar -C ./release/${target} -czvf ethetl-${version}-${target}.tar.gz bin schemas configs
      - name: update release to github
        shell: bash
        # Reference: https://cli.github.com/manual/gh_release_upload
        run: |
          version="${{ needs.create_release.outputs.version }}"
          target="${{ steps.target.outputs.target }}"
          gh release upload ${version} ethetl-${version}-${target}.* --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_docker:
    name: docker image
    runs-on: ubuntu-latest
    needs: [create_release, publish_linux]
    steps:
      - uses: actions/checkout@v3
      - name: download binaries
        run: |
          version="${{ needs.create_release.outputs.version }}"
          curl -sSLfo /tmp/ethetl.tar.gz https://github.com/deepeth/mars/releases/download/${version}/ethetl-${version}-x86_64-unknown-linux-gnu.tar.gz
          mkdir -p docker/release
          tar -C docker/release -zxvf /tmp/ethetl.tar.gz
      - name: login to GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build & push
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          pull: true
          tags: ghcr.io/deepeth/mars:${{ needs.create_release.outputs.version }}
