name: Rust

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build
      - name: Run lint
        run: cargo clippy -- -Dwarnings
      - name: Run unit tests
        run: cargo test --verbose